name: Spawn
version: '1.0-SNAPSHOT'
main: me.libelula.spawn.Spawn
api-version: '1.21'
authors:
  - "Diego D'Onofrio"
description: "Spigot Server Spawn Control Plugin"
depend:
  - WorldGuard
  - WorldEdit
permissions:
  spawn.bypass:
    description: "Allows the player to bypass spawn restrictions"
    default: false
  spawn.admin:
    description: "Gives admin-level permissions for the Spawn plugin"
    default: op
  spawn.bypass.delay:
    description: "Allows the player to bypass teleport delay"
    default: false
  spawn.player.use.spawn.0:
    description: "Spawn command teleport the player to the first spawn region"
    default: false
  spawn.player.use.spawn.1:
    description: "Spawn command teleport the player to the second spawn region"
    default: false
  spawn.player.use.spawn.2:
    description: "Spawn command teleport the player to the third spawn region"
    default: false
  spawn.player.use.spawn.3:
    description: "Spawn command teleport the player to the fourth spawn region"
    default: false
  spawn.player.use.spawn.4:
    description: "Spawn command teleport the player to the fifth spawn region"
    default: false
  spawn.player.use.spawn.5:
    description: "Spawn command teleport the player to the sixth spawn region"
    default: false
  spawn.player.use.spawn.6:
    description: "Spawn command teleport the player to the seventh spawn region"
    default: false
  spawn.player.use.spawn.7:
    description: "Spawn command teleport the player to the eighth spawn region"
    default: false
  spawn.player.use.spawn.8:
    description: "Spawn command teleport the player to the ninth spawn region"
    default: false
  spawn.player.use.spawn.9:
    description: "Spawn command teleport the player to the tenth spawn region"
    default: false
commands:
  spawn:
    description: Teleports the player to the spawn point.
    usage: /spawn
    aliases: []
    permission: spawn.player.use
    permission-message: "§cYou do not have permission to use this command."
    description-extended: |
      User Commands:
        /spawn - Teleport to the highest spawn point allowed by your permissions.
      Admin Commands:
        /spawn addsp - Add a new spawn point in the current region.
        /spawn clear - Clear all spawn points in the current region.
        /spawn allow - (Demo) Allow certain block interactions.
        /spawn allow-command - (Demo) Allow certain commands here.
